export type HistoricalDataType = {
    timezone: string,
    state_code: string,
    country_code: string,
    lat: number,
    lon: number,
    city_name: string,
    station_id: string,
    data: {
        rh: number,
        max_wind_spd_ts: number,
        t_ghi: number,
        max_wind_spd: number,
        solar_rad: number,
        wind_gust_spd: number,
        max_temp_ts: number,
        min_temp_ts: number,
        clouds: number,
        max_dni: number,
        precip_gpm: number,
        wind_spd: number,
        slp: number,
        ts: number,
        max_ghi: number,
        temp: number,
        pres: number,
        dni: number,
        dewpt: number,
        snow: number,
        dhi: number,
        precip: number,
        wind_dir: number,
        max_dhi: number,
        ghi: number,
        max_temp: number,
        t_dni: number,
        max_uv: number,
        t_dhi: number,
        datetime: string,
        t_solar_rad: number,
        min_temp: number,
        max_wind_dir: number,
        snow_depth: null | any
    }[],
    sources: string[],
    city_id: string
}